({
  ip: { js: 'string', metadata: { pg: 'inet' } },
  /** Autogenerated by Postgres UUID v4 */
  genUUID: { js: 'string', metadata: { pg: 'uuid DEFAULT gen_random_uuid()' } },
  // TODO: How to describe array of enumerable strings?
  vehicleKindArray: {
    js: {
      array: {
        // TODO: Can you reference one custom type as a type of items within other custom collection type?
        enum: [
          'bicycle',
          'scooter',
          'motorcycle',
          'car',
          'van',
          'truck',
          'bus',
        ],
        // TODO: Is it limiting length of an array instead of array item?
        length: { max: 32 },
        note: 'A kind of a vehicle',
      },
    },
    metadata: { pg: 'varchar(32)[]' },
    checkType(src, path) {
      if (!Array.isArray(src)) {
        return `Field "${path}" not a vehicleKindArray 1`;
      }
      for (const value of src) {
        if (typeof value !== 'string')
          return `Field "${path}" not a vehicleKindArray 2`;
        else if (!this.js.array.enum.includes(value))
          return `Field "${path}" not a vehicleKindArray 3`;
      }
      return null;
    },
    construct() {}
  },
});
