({
  Entity: {
    note: 'A parking for electric vehicles',
  },
  /* Metarhia does not support UUID for primary key.
    That's intentional decision due to performance concerns.
    So in the case of UUID needed you must declare separate field (e.g. `guid`)
    to hold generated identifier and mark it as unique. */

  /**
   * Universally unique identifier for cross-system or public communication about the entity.
   * Used as a separate ID key only!
   * All internal entity references uses primary generated as identity key of type BigInt.
   */
  guid: {
    /** Custom type: autogenerated by Postgres UUID */
    type: 'genUUID',
    unique: true,
  },
  name: 'string',
  // TODO: How to describe domain models that not entity to be stored as JSONB in DB?
  /** JSON Schema example
   * @example
   * ```json
    "address": {
      "type": "object",
      "properties": {
        "country": { "type": "string" },
        "state": { "type": "string" },
        "city": { "type": "string" },
        "streetAddress": { "type": "string" }
      },
      "additionalProperties": false,
      "required": ["country", "city", "streetAddress"]
    }
    ```
   */
  address: 'json',
  // TODO: How to describe domain models that not entity to be stored as JSONB in DB?
  /** JSON Schema example
   * @example
   * ```json
   {
      "title": "Longitude and Latitude Values",
      "description": "A geographical coordinate.",
      "type": "object",
      "properties": {
        "latitude": {
          "type": "number",
          "minimum": -90,
          "maximum": 90
        },
        "longitude": {
          "type": "number",
          "minimum": -180,
          "maximum": 180
        }
      },
      "required": [ "latitude", "longitude" ]
    }
    ```
   */
  location: 'json',
  // TODO: How to describe one-to-many relation at the "one" side?
  // spots: { many: 'Spot' },  // <-- this creates many-to-many
  // chargers: { many: 'ElectricCharger' }, // <-- this creates many-to-many
});
